/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testing;

import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author The Coders
 */
public final class up_img extends javax.swing.JFrame {

    /**
     * Creates new form up_img
     */
    private Connection conn;
    private Statement stat;
    private ResultSet rs;
    private DefaultTableModel model;
    
    public up_img() {
        initComponents();
        conn = koneksi.koneksi();
        model = new DefaultTableModel();
        table_coba.setModel(model);
        model.addColumn("id");
        model.addColumn("Gambar");
        tabel();
    }
public void tabel(){
    try {
        model.fireTableDataChanged();
        model.getDataVector().removeAllElements();
        String sql ="select * from img_up";
        stat = conn.createStatement();
        rs = stat.executeQuery(sql);
        while (rs.next()) {
            Object[] o = new Object[2];
            o[0] = rs.getString("id");
            o[1] = rs.getString("img");
            model.addRow(o);
            
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_img = new javax.swing.JLabel();
        btn_chooser = new javax.swing.JButton();
        lbl_imgclik = new javax.swing.JLabel();
        btn_insertimg = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_coba = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_img.setBackground(new java.awt.Color(255, 255, 51));

        btn_chooser.setText("chooser");
        btn_chooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chooserActionPerformed(evt);
            }
        });

        btn_insertimg.setText("insert to database");
        btn_insertimg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertimgActionPerformed(evt);
            }
        });

        table_coba.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_coba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_cobaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_coba);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_img, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(lbl_imgclik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btn_chooser)
                        .addGap(18, 18, 18)
                        .addComponent(btn_insertimg)
                        .addGap(0, 341, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_chooser)
                    .addComponent(btn_insertimg))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(lbl_img, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_imgclik, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_chooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chooserActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new  JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        lbl_imgclik.setText(filename);
        Image getAbsolutePath = null;
        ImageIcon icon = new ImageIcon(filename);
        Image image = icon.getImage().getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.SCALE_SMOOTH);
        lbl_img.setIcon(icon);
    }//GEN-LAST:event_btn_chooserActionPerformed

    private void btn_insertimgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertimgActionPerformed
        // TODO add your handling code here:
        
        try {
            String image = lbl_imgclik.getText();
            image = image.replace("\\", "\\\\");
            
            String sql = "insert into img_up (img) values (?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, image);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "insert foto berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_insertimgActionPerformed

    private void table_cobaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_cobaMouseClicked
        // Table mouse click
        int baris = table_coba.getSelectedRow();
        String id = model.getValueAt(baris, 0).toString();
        try {
           String sql ="select*from img_up where id ='"+id+"'";
           stat=conn.createStatement();
           rs = stat.executeQuery(sql);
            if (rs.next()) {
                lbl_imgclik.setText(rs.getString("img"));
            }else{
                JOptionPane.showMessageDialog(this, "gagall");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_table_cobaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(up_img.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(up_img.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(up_img.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(up_img.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new up_img().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chooser;
    private javax.swing.JButton btn_insertimg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JLabel lbl_imgclik;
    private javax.swing.JTable table_coba;
    // End of variables declaration//GEN-END:variables
}

