package latianedo;
    
public class NewClass1 {
    public static void main(String[] args) {
        System.out.println("Program 1");
//        String username = "ADMIN";
//        int harga = 2500;
//        System.out.println("USERNAME = " + username);
//        System.out.println("Nilai Harga = ");
//        System.out.println(harga);
        System.out.println("");
        System.out.println("");
        System.out.println("");                
        System.out.println("Program 2");
//        final double pi = 3.14;
//        double radius = 30;
//        System.out.println("Keliling = " + 2 * pi * radius);
        System.out.println("");
        System.out.println("");
        System.out.println("");                
        System.out.println("Program 3");               
//        int a = 10;
//        int b = 20;
//        int c = 25;
//        int d = 25;
//        System.out.println("a + b = " + (a + b));
//        System.out.println("a - b = " + (a - b));
//        System.out.println("a * b = " + (a * b));
//        System.out.println("b / a = " + (b / a));
//        System.out.println("b % a = " + (b % a));
//        System.out.println("c % a = " + (c % a));
        System.out.println("");
        System.out.println("");
        System.out.println("");                
//        System.out.println("Program 4");
//        int c = 10;
//        int d = 10;
//        int C = c++;
//        int D = ++d;
//        System.out.println("--------------------");
//        System.out.println("Nilai c post Increment" + (C));
//        System.out.println("Nilai d pre Increment" + (D));
//        System.out.println("--------------------");
        System.out.println("");
        System.out.println("");
        System.out.println("");                
        System.out.println("Program 5");
//        int c = 10;
//        int d = 10;
//        int C = c--;
//        int D = --d;
//        System.out.println("--------------------");
//        System.out.println("Nilai c post Increment" + (C));
//        System.out.println("Nilai d pre Increment" + (D));
//        System.out.println("--------------------");
        System.out.println("");
        System.out.println("");
        System.out.println("");                
        System.out.println("Program 6");
//        int a = 20;
//        System.out.println(a += 5);
//        int b = 7;
//        System.out.println(b -= 5);
//        int c = 9;
//        System.out.println(c *= 3);
//        float d = 10;
//        System.out.println(d /= 3);
//        int e = 10;
//        System.out.println(e %= 3);
        System.out.println("");
        System.out.println("");
        System.out.println("");                
        System.out.println("Program 7");
//        int A = 10;
//        int B = 7;
//        Boolean hasil;
//        hasil = A > B;
//        System.out.println(hasil);
//        hasil = A < B;
//        System.out.println(hasil);
//        hasil = A >= B;
//        System.out.println(hasil);
//        hasil = A <= B;
//        System.out.println(hasil);
//        hasil = A == B;
//        System.out.println(hasil);
//        hasil = A != B;
//        System.out.println(hasil);
        System.out.println("");
        System.out.println("");
        System.out.println("");                
        System.out.println("Program 8");
//        int A = 75;
//        int B = 80;
//        int C = 90;
//        boolean a = A>B && B<C;
//        boolean b = A<B && B<C;
//        System.out.println(a);
//        System.out.println(b);
        System.out.println("");
        System.out.println("");
        System.out.println("");                
        System.out.println("Program 9");
        int A = 75;
        int B = 80;
        int C = 90;
        boolean a = A>B && B<C || C<B;
        boolean b = A<B || B<C && C<B;
        System.out.println(a);
        System.out.println(b);
        System.out.println("");
        System.out.println("");
        System.out.println(""); 
        System.out.println("Program 10");
//        int A = 70;
//        int B = 90;
//        boolean a = A>B;
//        System.out.println(!a);
//        
        
    }    
}