
package latihan;

import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NIOKE
 */
public class latihan extends javax.swing.JFrame {

    /**
     * Creates new form latihan
     */
    private DefaultTableModel tablemodel;  
    private Connection conn;            
    private Statement st;
    private ResultSet rs;
    
    public latihan() {
        initComponents();
        conn = koneksi.koneksi();
        inittable();
        getDataSiswa();
    }   
    private void inittable(){
        tablemodel = new DefaultTableModel();
        Tabel_siswa.setModel(tablemodel);
        tablemodel.addColumn("id");
        tablemodel.addColumn("Nama");
        tablemodel.addColumn("Kelas");   
        
    }
    private void getDataSiswa(){
        tablemodel.getDataVector().removeAllElements();
        tablemodel.fireTableDataChanged();
        try {
            String sql = "select * from siswa";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            
            
            while (rs.next()) {                
                Object[] o = new Object[3];
                o[0] = rs.getString("id");
                o[1] = rs.getString("nama");
                o[2] = rs.getString("kelas");
                tablemodel.addRow(o);
            }
        } catch (SQLException e) {
            
        }

        
        
        
    
                   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel_siswa = new javax.swing.JTable();
        btn_ubah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_kelas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        btn_hapus = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tabel_siswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabel_siswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel_siswaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Tabel_siswaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel_siswa);

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama");

        jLabel2.setText("Kelas");

        txt_kelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_kelasKeyTyped(evt);
            }
        });

        jLabel3.setText("id");

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btn_tambah)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ubah)
                        .addGap(18, 18, 18)
                        .addComponent(btn_hapus))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_nama)
                            .addComponent(txt_kelas)
                            .addComponent(txt_id, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ubah)
                    .addComponent(btn_hapus)
                    .addComponent(btn_tambah))
                .addGap(18, 18, 18))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        //update
        //method untuk menyeleksi data yg akan diubah
//        int row = Tabel_siswa.getSelectedRow();
       
  
        //mengambil inputan untuk data yg akan diubah
        String id = (String) txt_id.getText(); 
        String nama = txt_nama.getText();
        String kelas = txt_kelas.getText();
        

        //lakukan perubahan data ke database
        conn = koneksi.koneksi();
        String query = "UPDATE siswa SET "
            + "nama=?,kelas=? "
            + "WHERE id=?";
        try {
            PreparedStatement statement = (PreparedStatement) conn.prepareStatement(query);
            statement.setString(1, nama);            
            statement.setString(2, kelas);            
            statement.setString(3, id);
            statement.executeUpdate();
            getDataSiswa();
            resetData();
            JOptionPane.showMessageDialog(this, "data telah diubah");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi error pada saat update data");
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void Tabel_siswaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel_siswaMousePressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_Tabel_siswaMousePressed

    private void Tabel_siswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel_siswaMouseClicked
        // TODO add your handling code here:
        try {
            //mendapatkan baris yang terseleksi
            int row=Tabel_siswa.getSelectedRow();
//            if (row == 1) {
//                return;
//            }
        
            //mengambil data dan ditampung
            String id = (String) tablemodel.getValueAt(row, 0);
            String nama = (String) tablemodel.getValueAt(row, 1);
            String kelas = (String) tablemodel.getValueAt(row, 2);
            

            //memberi data di setiap inputan
            txt_id.setText(id);
            txt_nama.setText(nama);
            txt_kelas.setText(kelas);
            txt_id.setEditable(false);
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_Tabel_siswaMouseClicked

    private void txt_kelasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kelasKeyTyped
        // TODO add your handling code here:
        char e = evt.getKeyChar();
        if (Character.isAlphabetic(e)) {
            JOptionPane.showMessageDialog(this, "Harus angka");
            evt.consume();
        }
    }//GEN-LAST:event_txt_kelasKeyTyped

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "delete from siswa where id = ?";
            PreparedStatement ps = (PreparedStatement) conn.prepareStatement(sql);
            ps.setString(1, txt_id.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Hapus berhasil");
            getDataSiswa();
            resetData();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Hapus gagal" + e.getMessage());
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        String id = (String) txt_id.getText(); 
        String nama = txt_nama.getText();
        String kelas = txt_kelas.getText();
        

        //lakukan perubahan data ke database
        conn = koneksi.koneksi();
        String query = "insert into siswa (id, nama, kelas) values(?,?,?)";
        try {
            PreparedStatement statement = (PreparedStatement) conn.prepareStatement(query);
            statement.setString(1, id);
            statement.setString(2, nama);            
            statement.setString(3, kelas);
            statement.executeUpdate();
            getDataSiswa();
            resetData();
            JOptionPane.showMessageDialog(this, "data telah tambahkan");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi error pada saat tambahkan data");
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void resetData() {
        txt_id.setText("");
        txt_nama.setText("");
        txt_kelas.setText("");
        getDataSiswa();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new latihan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabel_siswa;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_kelas;
    private javax.swing.JTextField txt_nama;
    // End of variables declaration//GEN-END:variables
}

   
