/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author The Coders
 */
public class User_Kembalian extends javax.swing.JFrame {

    
    private Connection conn;
    private Statement st;
    private ResultSet rs;
    private DefaultTableModel model;
    
    public User_Kembalian() {
        initComponents();
        conn = koneksi.koneksi();
        iniTable();
        getDataTable();
    }
    private void iniTable(){
        model = new DefaultTableModel();
        model.addColumn("KODE PEMINJAMAN");
        model.addColumn("ISBN");
        model.addColumn("JUDUL");
        model.addColumn("PENERBIT");
        model.addColumn("JUMLAH");
        model.addColumn("TANGGAL PEMINJAMAN");                       
        tabel_kembalikan.setModel(model);        
    }
    private void getDataTable(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            String sql = "select * from peminjaman";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {                
                Object[] o = new Object[6];
                o[0] = rs.getString("id_pinjam");
                o[1] = rs.getString("isbn_id");
                o[2] = rs.getString("judul");
                o[3] = rs.getString("penerbit");
                o[4] = rs.getString("jumlah_peminjaman");
                o[5] = rs.getString("tgl_pinjam");
                                
                model.addRow(o);
            }
        } catch (Exception e) {
        }
    }
    /**
;     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_kembalikan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_TanggalKembali = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_judul = new javax.swing.JLabel();
        lbl_isbn = new javax.swing.JLabel();
        lbl_penerbit = new javax.swing.JLabel();
        lbl_jumlah = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_kembalikan = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_idPinjam = new javax.swing.JLabel();
        lbl_tgl_pinjam = new javax.swing.JLabel();
        btn_home = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabel_kembalikan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_kembalikan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_kembalikanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_kembalikan);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("KEMBALIKAN BUKU");

        jLabel8.setText("TANGGAL KEMBALI");

        jLabel3.setText("JUDUL = ");

        lbl_judul.setText("-");

        lbl_isbn.setText("-");

        lbl_penerbit.setText("-");

        lbl_jumlah.setText("-");

        jLabel5.setText("JUMLAH = ");

        jLabel4.setText("PENERBIT = ");

        jLabel2.setText("ISBN = ");

        btn_kembalikan.setText("KEMBALIKAN BUKU");
        btn_kembalikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembalikanActionPerformed(evt);
            }
        });

        jLabel11.setText("TANGGAL PINJAM =");

        jLabel12.setText("ID PEMNIJAMAN =");

        lbl_idPinjam.setText("-");

        lbl_tgl_pinjam.setText("-");

        btn_home.setText("HOME");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_TanggalKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_kembalikan)
                                .addGap(18, 18, 18)
                                .addComponent(btn_home)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(lbl_judul))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(lbl_isbn)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_tgl_pinjam)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_penerbit)
                            .addComponent(lbl_jumlah)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_idPinjam)))
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lbl_penerbit))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lbl_jumlah)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lbl_isbn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbl_judul))))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_tgl_pinjam)
                    .addComponent(jLabel12)
                    .addComponent(lbl_idPinjam))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_TanggalKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_kembalikan)
                    .addComponent(btn_home))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabel_kembalikanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_kembalikanMouseClicked
        // TODO add your handling code here:
        int baris = tabel_kembalikan.getSelectedRow();
        String isbn_id =  model.getValueAt(baris, 0).toString();
        try {
            String sql = "select * from peminjaman where id_pinjam = '"+isbn_id+"'";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            if (rs.next()) {
                
                lbl_isbn.setText(rs.getString("isbn_id"));
                lbl_judul.setText(rs.getString("judul"));
                lbl_penerbit.setText(rs.getString("penerbit"));
                lbl_jumlah.setText(rs.getString("jumlah_peminjaman"));              
                lbl_idPinjam.setText(rs.getString("id_pinjam"));
                lbl_tgl_pinjam.setText(rs.getString("tgl_pinjam"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tabel_kembalikanMouseClicked

    private void btn_kembalikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembalikanActionPerformed
        // TODO add your handling code here:
        String isbn = lbl_isbn.getText();
        String sql1 = "insert into pengembalian (isbn_id,tgl_pinjam,tgl_kembali,jumlah_pengembalian,id_pinjam,judul,penerbit) values (?,?,?,?,?,?,?)";
        String sql2 = "delete from peminjaman where isbn_id = ?";
        String sql3 = "delete from pengembalian where isbn_id = ?";
        try {            
            PreparedStatement ps = conn.prepareStatement(sql1);
            ps.setString(1, lbl_isbn.getText());
            ps.setString(2, lbl_tgl_pinjam.getText());
            ps.setString(3, txt_TanggalKembali.getText());
            ps.setString(4, lbl_jumlah.getText());
            ps.setString(5, lbl_idPinjam.getText());
            ps.setString(6, lbl_judul.getText());
            ps.setString(7, lbl_penerbit.getText());            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "pengembalian buku berhasil");
            getDataTable();
            txt_TanggalKembali.setText("");
                try {
                    PreparedStatement pst = conn.prepareStatement(sql2);
                    pst.setString(1, isbn);
                    pst.executeUpdate();
                    getDataTable();
                    try {
                        PreparedStatement ppst = conn.prepareStatement(sql3);
                        ppst.setString(1, isbn);
                        ppst.executeUpdate();
                        getDataTable();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e.getMessage());
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_kembalikanActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
        new USER().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Kembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Kembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Kembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Kembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Kembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_kembalikan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_idPinjam;
    private javax.swing.JLabel lbl_isbn;
    private javax.swing.JLabel lbl_judul;
    private javax.swing.JLabel lbl_jumlah;
    private javax.swing.JLabel lbl_penerbit;
    private javax.swing.JLabel lbl_tgl_pinjam;
    private javax.swing.JTable tabel_kembalikan;
    private javax.swing.JTextField txt_TanggalKembali;
    // End of variables declaration//GEN-END:variables
}
