/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihan_3;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NIOKE
 */
public class latihan extends javax.swing.JFrame {

    /**
     * Creates new form latihan
     */
    private Connection conn;
    private Statement st;
    private ResultSet rs;
    private DefaultTableModel model;
    public latihan() {
        initComponents();
        conn = koneksi.koneksi();
        iniTable();
        getDataSiswa();
    }
    private void iniTable(){
        model = new DefaultTableModel();
        tabel_siswa.setModel(model);
        model.addColumn("ID");
        model.addColumn("NAMA");
        model.addColumn("KELAS");
        model.addColumn("GENDER");
        model.addColumn("AGAMA");
        model.addColumn("HOBI");        
    }
    private void getDataSiswa(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            String sql = "select * from siswa_2";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {                
                Object[] o = new Object[6];
                o[0] = rs.getString("id");
                o[1] = rs.getString("nama");
                o[2] = rs.getString("kelas");
                o[3] = rs.getString("gender");
                o[4] = rs.getString("agama");
                o[5] = rs.getString("hobi");
                model.addRow(o);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    private void refresh(){
        txt_id.setText("");
        txt_nama.setText("");
        txt_kelas.setText("");
        rb_pria.setSelected(false);
        rb_wanita.setSelected(false);
        cmb_agama.setSelectedIndex(0);
        cb_ngoding.setSelected(false);
        cb_menulis.setSelected(false);
        cb_membaca.setSelected(false);
        buttonGroup1.clearSelection();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_siswa = new javax.swing.JTable();
        txt_id = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_kelas = new javax.swing.JTextField();
        rb_pria = new javax.swing.JRadioButton();
        rb_wanita = new javax.swing.JRadioButton();
        cmb_agama = new javax.swing.JComboBox<>();
        cb_ngoding = new javax.swing.JCheckBox();
        cb_menulis = new javax.swing.JCheckBox();
        cb_membaca = new javax.swing.JCheckBox();
        txt_cari = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_create = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("APLIKASI");

        tabel_siswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_siswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_siswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_siswa);

        buttonGroup1.add(rb_pria);
        rb_pria.setText("Pria");

        buttonGroup1.add(rb_wanita);
        rb_wanita.setText("Wanita");
        rb_wanita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_wanitaActionPerformed(evt);
            }
        });

        cmb_agama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "Islam", "Kristen", "Hindu", "Budha", "Konghucu" }));

        cb_ngoding.setText("Ngoding");

        cb_menulis.setText("Menulis");
        cb_menulis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_menulisActionPerformed(evt);
            }
        });

        cb_membaca.setText("Membaca");

        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });

        jLabel2.setText("ID");

        jLabel3.setText("NAMA");

        jLabel4.setText("KELAS");

        jLabel5.setText("GENDER");

        jLabel6.setText("AGAMA");

        jLabel7.setText("HOBY");

        jLabel8.setText("CARI BERSARAKAN NAMA");

        btn_create.setText("CREATE");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });

        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_refresh.setText("REFRESH");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(337, 337, 337))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_create)
                                .addGap(18, 18, 18)
                                .addComponent(btn_update)
                                .addGap(18, 18, 18)
                                .addComponent(btn_hapus)
                                .addGap(18, 18, 18)
                                .addComponent(btn_refresh))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb_pria)
                                .addGap(18, 18, 18)
                                .addComponent(rb_wanita))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_nama, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmb_agama, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_kelas, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_cari, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(cb_ngoding)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cb_menulis)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cb_membaca)))
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 239, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_pria)
                            .addComponent(rb_wanita)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_agama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_ngoding)
                    .addComponent(jLabel7)
                    .addComponent(cb_menulis)
                    .addComponent(cb_membaca))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_create)
                    .addComponent(btn_update)
                    .addComponent(btn_hapus)
                    .addComponent(btn_refresh))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cb_menulisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_menulisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_menulisActionPerformed

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
        // TODO add your handling code here:
        //variable untuk gender radiobutton
        String jenis_kelamin;
        if(rb_pria.isSelected() == true){
            jenis_kelamin = "Pria";
        }else{
            jenis_kelamin = "Wanita";
        }
        
        //variable untuk hobi
        String h_ngoding = "", h_menulis = "", h_membaca = "", hobi;
        
        if (cb_ngoding.isSelected() == true) {
            h_ngoding = "Ngoding";
        }
        if (cb_menulis.isSelected() == true) {
            h_menulis = "Menulis";
        }
        if (cb_membaca.isSelected() == true) {
            h_membaca = "Membaca";
        }       
        
        hobi = h_ngoding + " " + h_menulis + " " + h_membaca;
                
                
        //ambil inputan dari form
        String id  = txt_id.getText();
        String nama = txt_nama.getText();
        String kelas =  txt_kelas.getText();
        String agama = cmb_agama.getSelectedItem().toString();
        
        try {
            String sql = "insert into siswa_2 (nama,kelas,gender,agama,hobi) values (?,?,?,?,?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, nama);
            pst.setString(2, kelas);
            pst.setString(3, jenis_kelamin);
            pst.setString(4, agama);
            pst.setString(5, hobi);            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "tambah data berhasil");
            getDataSiswa();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "tambah data gagal\n" + e.getMessage());
        }
        
        
        
//        //variabel untuk radio button 
//        String jenis_kelamin;
//        
//        if(rb_pria.isSelected() == true){
//            jenis_kelamin = "Pria";
//        }else{
//            jenis_kelamin = "Wanita";
//        }
//        String h_musik = "", h_ngoding = "", h_rebahan = "", hobi;
//        
//        if (cb_musikal.isSelected() == true) {
//            h_musik = "Musikal";
//        }
//        if (cb_ngoding.isSelected() == true) {
//            h_ngoding = "Ngoding";
//        }
//        if (cb_rebahan.isSelected() == true) {
//            h_rebahan = "Rebahan";
//        }       
//        
//        hobi = h_musik + " " + h_ngoding + " " + h_rebahan;
//        
//        String id = txt_id.getText();
//        String nama = txt_nama.getText();
//        String kelas = (String) cmb_kelas.getSelectedItem();
//        String provinsi = (String) cmb_provinsi.getSelectedItem();
//        
//        
//        
//        //lakukan perubahan pada database
//        conn = latihan2.koneksi.koneksi();
//        String sql = "insert into siswa_2 (nama,kelas,gender,provinsi,hobi) values(?,?,?,?,?)";
//        try {
//            PreparedStatement pst = conn.prepareStatement(sql);
//            pst.setString(1, nama);
//            pst.setString(2, kelas);
//            pst.setString(3, jenis_kelamin);
//            pst.setString(4, provinsi);
//            pst.setString(5, hobi);
//            pst.executeUpdate();
//            JOptionPane.showMessageDialog(this, "Tambah Data Berhasil");
//            refresh();
//        } catch (SQLException e) {
//            JOptionPane.showMessageDialog(this, e.getMessage());
//        }
    }//GEN-LAST:event_btn_createActionPerformed

    private void rb_wanitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_wanitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_wanitaActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:    
        try {
            String sql = "delete from siswa_2 where id = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txt_id.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Hapus Data Berhasil");
            getDataSiswa();
            refresh();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hapus Data Gagal" + e.getMessage());
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tabel_siswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_siswaMouseClicked
        // TODO add your handling code here:
        int baris = tabel_siswa.getSelectedRow();
        String id = model.getValueAt(baris, 0).toString();
        try {
            String sql = "select * from siswa_2 where id = '" + id + "'";
            Statement stat = conn.createStatement();
            rs = stat.executeQuery(sql);
            
              if (rs.next()) {
                  txt_id.setText(rs.getString("id"));
                  txt_nama.setText(rs.getString("nama"));
                  txt_kelas.setText(rs.getString("kelas"));                  
                  if (rs.getString("gender").equals("Pria")) {
                      rb_pria.setSelected(true);
                  } else {
                      rb_wanita.setSelected(true);
                  }
                  cmb_agama.setSelectedItem(rs.getString("agama"));
                  if (rs.getString("hobi").contains("Ngoding")) {
                     cb_ngoding.setSelected(true);
                  }else{
                      cb_ngoding.setSelected(false);
                  }                  
                  if (rs.getString("hobi").contains("Menulis")) {
                     cb_menulis.setSelected(true);
                  }else{
                      cb_ngoding.setSelected(false);
                  }                  
                  if (rs.getString("hobi").contains("Membaca")) {
                     cb_membaca.setSelected(true);
                  }else{
                      cb_ngoding.setSelected(false);
                  }
              }               
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }                        
    }//GEN-LAST:event_tabel_siswaMouseClicked

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        //variable untuk gender radiobutton
        String gender;
        if(rb_pria.isSelected() == true){
            gender = "Pria";
        }else{
            gender = "Wanita";
        }
        
        //variable untuk hobi
        String hobi_1 = "",hobi_2 = "",hobi_3 = "",hobi;
        if(cb_ngoding.isSelected() == true){
            hobi_1 = "Ngoding";            
        }
        if(cb_menulis.isSelected() == true){
            hobi_1 = "Menulis";            
        }
        if(cb_membaca.isSelected() == true){
            hobi_1 = "Membaca";            
        }
        
        
        hobi = hobi_1 + " " + hobi_2 + " " + hobi_3;
                
                
        //ambil inputan dari form
        String id  = txt_id.getText();
        String nama = txt_nama.getText();
        String kelas =  txt_kelas.getText();
        String agama = cmb_agama.getSelectedItem().toString();
        
        try {
            String sql = "update siswa_2 set nama = ?,kelas = ?,gender = ?,agama = ?,hobi = ? where id = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, nama);
            pst.setString(2, kelas);
            pst.setString(3, gender);
            pst.setString(4, agama);
            pst.setString(5, hobi);            
            pst.setString(6, id);            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "tambah data berhasil");
            getDataSiswa();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "tambah data gagal\n" + e.getMessage());
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
        // TODO add your handling code here:
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        try {
            String sql = "select * from siswa_2 where nama LIKE '%" + txt_cari.getText() + "%'" ;
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {                
                Object[] o = new Object[6];
                o[0] = rs.getString("id");
                o[1] = rs.getString("nama");
                o[2] = rs.getString("kelas");
                o[3] = rs.getString("gender");
                o[4] = rs.getString("agama");
                o[5] = rs.getString("hobi");
                model.addRow(o);                
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txt_cariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new latihan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_create;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cb_membaca;
    private javax.swing.JCheckBox cb_menulis;
    private javax.swing.JCheckBox cb_ngoding;
    private javax.swing.JComboBox<String> cmb_agama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_pria;
    private javax.swing.JRadioButton rb_wanita;
    private javax.swing.JTable tabel_siswa;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_kelas;
    private javax.swing.JTextField txt_nama;
    // End of variables declaration//GEN-END:variables
}
