package latihan2;

import java.awt.Button;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NIOKE
 */
public class latihan extends javax.swing.JFrame {

    /**
     * Creates new form latihan
     */
    private Connection conn;
    private Statement st;
    private ResultSet rs;
    private DefaultTableModel model;    
    public latihan() {
        initComponents();
        conn = koneksi.koneksi();
        iniTable();
        getDataTable();
    }
    private void iniTable(){
       model = new DefaultTableModel();
       tabel_biodata.setModel(model);
       model.addColumn("ID");
       model.addColumn("NAMA");
       model.addColumn("KELAS");
       model.addColumn("GENDER");
       model.addColumn("PROVINSI");
       model.addColumn("HOBI");
    }
    private void getDataTable(){
        //remove si table trus set lagi
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            String sql = "select * from siswa_1";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {                
                Object[] o = new Object[6];
                o[0] = rs.getString("id");
                o[1] = rs.getString("nama");
                o[2] = rs.getString("kelas");
                o[3] = rs.getString("gender");                
                o[4] = rs.getString("provinsi");
                o[5] = rs.getString("hobi");
                model.addRow(o);
            }
        } catch (SQLException e) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        rb_pria = new javax.swing.JRadioButton();
        rb_wanita = new javax.swing.JRadioButton();
        cb_ngoding = new javax.swing.JCheckBox();
        cb_rebahan = new javax.swing.JCheckBox();
        cb_musikal = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_create = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_biodata = new javax.swing.JTable();
        cmb_kelas = new javax.swing.JComboBox<>();
        cmb_provinsi = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        txt_cari = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("APLIKASI");

        txt_id.setEditable(false);

        buttonGroup1.add(rb_pria);
        rb_pria.setText("PRIA");
        rb_pria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_priaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_wanita);
        rb_wanita.setText("WANITA");
        rb_wanita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_wanitaActionPerformed(evt);
            }
        });

        cb_ngoding.setText("Ngoding");

        cb_rebahan.setText("Rebahan");

        cb_musikal.setText("Musikal");

        jLabel2.setText("ID");

        jLabel3.setText("NAMA");

        jLabel4.setText("KELAS");

        jLabel5.setText("GENDER");

        jLabel6.setText("PROVINSI");

        jLabel7.setText("HOBI");

        btn_create.setText("CREATE");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });

        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setText("DELETE");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        tabel_biodata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_biodata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_biodataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_biodata);

        cmb_kelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "X", "XI", "XII" }));

        cmb_provinsi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "Jawa Timur", "Jawa Tengah", "Jawa Barat" }));

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });

        jLabel8.setText("Cari berdasarkan nama: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_create)
                                .addGap(18, 18, 18)
                                .addComponent(btn_update)
                                .addGap(18, 18, 18)
                                .addComponent(btn_delete)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cb_ngoding)
                                        .addGap(18, 18, 18)
                                        .addComponent(cb_rebahan)
                                        .addGap(18, 18, 18)
                                        .addComponent(cb_musikal))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cmb_provinsi, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cmb_kelas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(rb_pria)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rb_wanita)
                                            .addGap(8, 8, 8))
                                        .addComponent(txt_nama, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_id, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmb_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_pria)
                            .addComponent(rb_wanita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cmb_provinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_ngoding)
                            .addComponent(cb_rebahan)
                            .addComponent(cb_musikal)
                            .addComponent(jLabel7)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_create)
                    .addComponent(btn_update)
                    .addComponent(btn_delete)
                    .addComponent(jButton1))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
        // TODO add your handling code here:
        
        //variabel untuk radio button 
        String jenis_kelamin;
        
        if(rb_pria.isSelected() == true){
            jenis_kelamin = "Pria";
        }else{
            jenis_kelamin = "Wanita";
        }
        
        //CHECKBOX
        String h_musik = "0", h_ngoding = "", h_rebahan = "", hobi;
        
        if (cb_musikal.isSelected() == true) {
            h_musik = "Musikal";
        }
        if (cb_ngoding.isSelected() == true) {
            h_ngoding = "Ngoding";
        }
        if (cb_rebahan.isSelected() == true) {
            h_rebahan = "Rebahan";
        }       
        
        hobi = h_musik + " " + h_ngoding + " " + h_rebahan;
        
        String id = txt_id.getText();
        String nama = txt_nama.getText();
        String kelas = (String) cmb_kelas.getSelectedItem();
        String provinsi = (String) cmb_provinsi.getSelectedItem();
        
        
        
        //lakukan perubahan pada database
        conn = koneksi.koneksi();
        String sql = "insert into siswa_1 (nama,kelas,gender,provinsi,hobi) values(?,?,?,?,?)";
        try {
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, nama);
            pst.setString(2, kelas);
            pst.setString(3, jenis_kelamin);
            pst.setString(4, provinsi);
            pst.setString(5, hobi);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Tambah Data Berhasil");
            resetField();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
  
    }//GEN-LAST:event_btn_createActionPerformed

    private void resetField() {
        txt_id.setText("");
        txt_nama.setText("");
        cmb_kelas.setSelectedIndex(0);
        cmb_provinsi.setSelectedIndex(0);
        cb_musikal.setSelected(false);
        cb_ngoding.setSelected(false);
        cb_rebahan.setSelected(false);
        buttonGroup1.clearSelection();
        getDataTable();
    }
    
    private void rb_wanitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_wanitaActionPerformed
        // TODO add your handling code here:
        if (rb_wanita.isSelected()) {
            rb_pria.setSelected(false);
        }
    }//GEN-LAST:event_rb_wanitaActionPerformed

    private void rb_priaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_priaActionPerformed
        // TODO add your handling code here:
        if (rb_pria.isSelected()) {
            rb_wanita.setSelected(false);
        }
    }//GEN-LAST:event_rb_priaActionPerformed

    private void tabel_biodataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_biodataMouseClicked
        // TODO add your handling code here:
//        int row = tabel_biodata.getSelectedRow();
//        txt_id.setText(model.getValueAt(row, 0).toString());
//        txt_nama.setText(model.getValueAt(row, 1).toString());
//        cmb_kelas.setSelectedItem((String) model.getValueAt(row, 2));
//        if (model.getValueAt(row, 3).toString().equals("Pria")) {
//            rb_pria.setSelected(true);
//        } else {
//            rb_wanita.setSelected(true);
//        }
//        cmb_provinsi.setSelectedItem((String) model.getValueAt(row, 4));
//        if (model.getValueAt(row, 5).equals("Ngoding")) {
//            cb_ngoding.setSelected(true);
//        } else if(model.getValueAt(row, 5).equals("Ngoding Musikal")) {
//            cb_ngoding.setSelected(true);
//            cb_musikal.setSelected(true);
//        } else if(model.getValueAt(row, 5).equals("Ngoding Musikal")) {
//            cb_ngoding.setSelected(true);
//            cb_musikal.setSelected(true);
//        }  
//        txt_id.setEditable(false);
//
          int baris = tabel_biodata.getSelectedRow();
          String id = model.getValueAt(baris, 0).toString();
          try {
            String sql = "select * from siswa_1 where id = '" + id + "'";
            Statement stat = conn.createStatement();
            rs = stat.executeQuery(sql);
            
              if (rs.next()) {
                  txt_id.setText(rs.getString("id"));
                  txt_nama.setText(rs.getString("nama"));
                  cmb_kelas.setSelectedItem(rs.getString("kelas"));
                  if (rs.getString("gender").equals("Pria")) {
                      rb_pria.setSelected(true);
                  } else {
                      rb_wanita.setSelected(true);
                  }
                  cmb_provinsi.setSelectedItem(rs.getString("provinsi"));
                  if (rs.getString("hobi").contains("Musikal")) {
                     cb_musikal.setSelected(true);
                  } else {
                      cb_musikal.setSelected(false);
                  }
                  
                  if (rs.getString("hobi").contains("Rebahan")) {
                     cb_rebahan.setSelected(true);
                  } else {
                      cb_rebahan.setSelected(false);
                  }
                  
                  if (rs.getString("hobi").contains("Ngoding")) {
                     cb_ngoding.setSelected(true);
                  } else {
                     cb_ngoding.setSelected(false);
                  }
              }
            
        } catch (Exception e) {
        }
          
    }//GEN-LAST:event_tabel_biodataMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        resetField();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        //variabel untuk radio button 
        String jenis_kelamin;

        if(rb_pria.isSelected() == true){
            jenis_kelamin = "pria";
        }else{
            jenis_kelamin = "wanita";
        }
        String h_musik = "", h_ngoding = "", h_rebahan = "", hobi;
        
        if (cb_musikal.isSelected() == true) {
            h_musik = "Musikal";
        }
        if (cb_ngoding.isSelected() == true) {
            h_ngoding = "Ngoding";
        }
        if (cb_rebahan.isSelected() == true) {
            h_rebahan = "Rebahan";
        }       
        
        hobi = h_musik + " " + h_ngoding + " " + h_rebahan;
        
        String id = txt_id.getText();
        String nama = txt_nama.getText();
        String kelas = (String) cmb_kelas.getSelectedItem();
        String provinsi = (String) cmb_provinsi.getSelectedItem();
        
        
        
        //lakukan perubahan pada database
        conn = koneksi.koneksi();
        String sql = "update siswa_1 set "
                + "nama = ?, kelas = ?, gender = ?, provinsi = ?, hobi = ?"
                + "where id = ?";
        try {
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, nama);
            pst.setString(2, kelas);
            pst.setString(3, jenis_kelamin);
            pst.setString(4, provinsi);
            pst.setString(5, hobi);
            pst.setString(6, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Tambah Data Berhasil");
            resetField();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
        // TODO add your handling code here:
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            String sql = "SELECT * FROM siswa_1 WHERE nama LIKE '%"+txt_cari.getText()+"%'";
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            while (rs.next()) {                
                Object[] o = new Object[6];
                o[0] = rs.getString("id");
                o[1] = rs.getString("nama");
                o[2] = rs.getString("kelas");
                o[3] = rs.getString("gender");                
                o[4] = rs.getString("provinsi");
                o[5] = rs.getString("hobi");
                model.addRow(o);
            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_txt_cariKeyReleased

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "delete from siswa_1 where id = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txt_id.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Hapus data berhasil");
            getDataTable();
            resetField();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Hapus Gagal" + e.getMessage());
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new latihan().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_create;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cb_musikal;
    private javax.swing.JCheckBox cb_ngoding;
    private javax.swing.JCheckBox cb_rebahan;
    private javax.swing.JComboBox<String> cmb_kelas;
    private javax.swing.JComboBox<String> cmb_provinsi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_pria;
    private javax.swing.JRadioButton rb_wanita;
    private javax.swing.JTable tabel_biodata;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nama;
    // End of variables declaration//GEN-END:variables
}
