/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihan_gui_1;

import javax.swing.JOptionPane;
import jdk.internal.org.objectweb.asm.Opcodes;

/**
 *
 * @author NIOKE
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_nama = new javax.swing.JTextField();
        tf_alamat = new javax.swing.JTextField();
        tf_no_hp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        rb_laki = new javax.swing.JRadioButton();
        rb_ciwi = new javax.swing.JRadioButton();
        cb_jurusan = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        ckb_gaming = new javax.swing.JCheckBox();
        ckb_tidur = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("APLIKASI");

        jLabel1.setText("NAMA");

        jLabel3.setText("JENIS KELAMIN");

        jLabel4.setText("ALAMAT");

        jLabel5.setText("NO.HP");

        jButton1.setText("KIRIM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_laki);
        rb_laki.setText("laki");

        buttonGroup1.add(rb_ciwi);
        rb_ciwi.setText("ciwi");
        rb_ciwi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_ciwiActionPerformed(evt);
            }
        });

        cb_jurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih", "TITL", "TB", "RPL", "TPMI", "TKR", " ", " " }));
        cb_jurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_jurusanActionPerformed(evt);
            }
        });

        jLabel6.setText("JURUSAN");

        ckb_gaming.setText("gaming");

        ckb_tidur.setText("tidur");

        jLabel9.setText("hoby");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckb_gaming)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(tf_nama)
                        .addComponent(tf_alamat)
                        .addComponent(tf_no_hp)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rb_laki)
                            .addGap(18, 18, 18)
                            .addComponent(rb_ciwi))
                        .addComponent(cb_jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ckb_tidur))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rb_laki)
                    .addComponent(rb_ciwi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_no_hp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb_jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckb_gaming)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckb_tidur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nama = tf_nama.getText();
        String jurusan = cb_jurusan.getSelectedItem().toString();
        String jenis_kelamin;
        String hobi = "";
        if(rb_laki.isSelected() == true){
            jenis_kelamin = "laki laki";
        }else{
            jenis_kelamin = "perempuan";
        }
        if(ckb_gaming.isSelected()){
            hobi += "gaming";
        }
        if(ckb_tidur.isSelected()){
            hobi += "tidur";
        }        
        String alamat = tf_alamat.getText();
        String no_hp = tf_no_hp.getText();
         if(nama.equals("") || jenis_kelamin.equals("") || alamat.equals("") || no_hp.equals("")){
             JOptionPane.showMessageDialog(this, "data kosong woii");
         }else{
             JOptionPane.showMessageDialog(this, "nama = " + nama + "\njenis kelamin = " + jenis_kelamin + "\nalamat = " + alamat + "\nno hp = "  + no_hp + "\nJurusan: " + jurusan + "\nhoby = " + hobi);
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb_jurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_jurusanActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_cb_jurusanActionPerformed

    private void rb_ciwiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_ciwiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_ciwiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_jurusan;
    private javax.swing.JCheckBox ckb_gaming;
    private javax.swing.JCheckBox ckb_tidur;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rb_ciwi;
    private javax.swing.JRadioButton rb_laki;
    private javax.swing.JTextField tf_alamat;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JTextField tf_no_hp;
    // End of variables declaration//GEN-END:variables
}
