/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javagui.view;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author sholehudin
 */
public class mainview extends javax.swing.JFrame {

    /**
     * Creates new form mainview
     */
    public mainview() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodypanel = new javax.swing.JPanel();
        menupanel = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        studying = new javax.swing.JButton();
        addfriend = new javax.swing.JButton();
        setting = new javax.swing.JButton();
        btn_logout = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        isiHome = new javax.swing.JPanel();
        welcome = new javax.swing.JLabel();
        created = new javax.swing.JLabel();
        labelnama = new javax.swing.JTextField();
        labelemail = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        confirm = new javax.swing.JLabel();
        labelconfirm = new javax.swing.JTextField();
        copyright = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnsignup = new javax.swing.JButton();
        btnsigin = new javax.swing.JButton();
        labelpass = new javax.swing.JPasswordField();
        isiaddfriend = new javax.swing.JPanel();
        juduladd = new javax.swing.JLabel();
        with = new javax.swing.JLabel();
        facebook = new javax.swing.JButton();
        whatsapp = new javax.swing.JButton();
        tf_link = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bt_link = new javax.swing.JButton();
        isistudy = new javax.swing.JPanel();
        desain = new javax.swing.JButton();
        script1 = new javax.swing.JButton();
        guijava = new javax.swing.JButton();
        python = new javax.swing.JButton();
        javascript = new javax.swing.JButton();
        java3 = new javax.swing.JButton();
        jjudul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("javaGUI");

        menupanel.setBackground(new java.awt.Color(0, 0, 0));
        menupanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        judul.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 255));
        judul.setText("SASKEH_CODE");

        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        studying.setText("STUDY");
        studying.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studyingActionPerformed(evt);
            }
        });

        addfriend.setText("Friends");
        addfriend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addfriendActionPerformed(evt);
            }
        });

        setting.setText("ABOUT");
        setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingActionPerformed(evt);
            }
        });

        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_logoutMousePressed(evt);
            }
        });

        jLabel3.setText("LOGOUT");

        javax.swing.GroupLayout btn_logoutLayout = new javax.swing.GroupLayout(btn_logout);
        btn_logout.setLayout(btn_logoutLayout);
        btn_logoutLayout.setHorizontalGroup(
            btn_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_logoutLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        btn_logoutLayout.setVerticalGroup(
            btn_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout menupanelLayout = new javax.swing.GroupLayout(menupanel);
        menupanel.setLayout(menupanelLayout);
        menupanelLayout.setHorizontalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menupanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(judul))
                    .addGroup(menupanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studying)
                            .addGroup(menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addfriend)
                                .addComponent(setting))
                            .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menupanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menupanelLayout.setVerticalGroup(
            menupanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(judul)
                .addGap(54, 54, 54)
                .addComponent(home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studying)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addfriend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(setting)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        mainPanel.setLayout(new java.awt.CardLayout());

        isiHome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        welcome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        welcome.setText("Welcome to Saskeh_Code");

        created.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        created.setForeground(new java.awt.Color(255, 0, 0));
        created.setText("*Create your account");

        labelemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelemailActionPerformed(evt);
            }
        });

        username.setText("Username");

        email.setText("e-mail");

        password.setText("Password");

        confirm.setText("Confirm Password");

        labelconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelconfirmActionPerformed(evt);
            }
        });

        copyright.setBackground(new java.awt.Color(0, 0, 0));
        copyright.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        copyright.setText("@Copyright 2020_Sam X");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("0R");

        btnsignup.setText("Sign up");
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });

        btnsigin.setText("Sign in");

        javax.swing.GroupLayout isiHomeLayout = new javax.swing.GroupLayout(isiHome);
        isiHome.setLayout(isiHomeLayout);
        isiHomeLayout.setHorizontalGroup(
            isiHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiHomeLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(welcome)
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(isiHomeLayout.createSequentialGroup()
                .addGroup(isiHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(isiHomeLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(isiHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirm)
                            .addComponent(password)
                            .addComponent(username)
                            .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, isiHomeLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(copyright)))
                .addContainerGap())
            .addGroup(isiHomeLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnsigin)
                .addGap(31, 31, 31)
                .addGroup(isiHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(isiHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelnama)
                        .addComponent(created)
                        .addComponent(labelemail)
                        .addComponent(labelconfirm)
                        .addComponent(labelpass, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(isiHomeLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(33, 33, 33)
                        .addComponent(btnsignup)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        isiHomeLayout.setVerticalGroup(
            isiHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcome)
                .addGap(27, 27, 27)
                .addGroup(isiHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(isiHomeLayout.createSequentialGroup()
                        .addComponent(username)
                        .addGap(40, 40, 40)
                        .addComponent(password)
                        .addGap(18, 18, 18)
                        .addComponent(confirm))
                    .addGroup(isiHomeLayout.createSequentialGroup()
                        .addComponent(created)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(isiHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62)
                .addGroup(isiHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnsignup)
                    .addComponent(btnsigin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(copyright)
                .addContainerGap())
        );

        mainPanel.add(isiHome, "card5");

        juduladd.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        juduladd.setText("Add Friends");

        with.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        with.setText("with");

        facebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javagui/GAMBAR/icons8-facebook-30.png"))); // NOI18N
        facebook.setText("facebook");
        facebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facebookActionPerformed(evt);
            }
        });

        whatsapp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javagui/GAMBAR/icons8-whatsapp-30.png"))); // NOI18N
        whatsapp.setText("whatsapp");

        tf_link.setText(".......");
        tf_link.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_linkActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("LINK");

        bt_link.setText("copy");

        javax.swing.GroupLayout isiaddfriendLayout = new javax.swing.GroupLayout(isiaddfriend);
        isiaddfriend.setLayout(isiaddfriendLayout);
        isiaddfriendLayout.setHorizontalGroup(
            isiaddfriendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiaddfriendLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(isiaddfriendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(isiaddfriendLayout.createSequentialGroup()
                        .addGroup(isiaddfriendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(isiaddfriendLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(tf_link, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bt_link))
                            .addGroup(isiaddfriendLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(with)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(isiaddfriendLayout.createSequentialGroup()
                        .addComponent(facebook)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(whatsapp)
                        .addGap(80, 80, 80))))
            .addGroup(isiaddfriendLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(juduladd)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        isiaddfriendLayout.setVerticalGroup(
            isiaddfriendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isiaddfriendLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(juduladd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(with)
                .addGap(44, 44, 44)
                .addGroup(isiaddfriendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facebook)
                    .addComponent(whatsapp))
                .addGap(80, 80, 80)
                .addGroup(isiaddfriendLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_link, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(bt_link))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        mainPanel.add(isiaddfriend, "card5");

        desain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javagui/GAMBAR/icons8-registry-editor-35.png"))); // NOI18N
        desain.setText("Desain");

        script1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javagui/GAMBAR/icons8-property-script-35.png"))); // NOI18N
        script1.setText("Script");

        guijava.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javagui/GAMBAR/icons8-java-35 (1).png"))); // NOI18N
        guijava.setText("JavaGUI");

        python.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javagui/GAMBAR/icons8-python-35.png"))); // NOI18N
        python.setText("Python");

        javascript.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javagui/GAMBAR/icons8-java-35.png"))); // NOI18N
        javascript.setText("JavaScript");

        java3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javagui/GAMBAR/icons8-java-file-35.png"))); // NOI18N
        java3.setText("Java");

        jjudul.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jjudul.setText("GOOD LUCK!");

        javax.swing.GroupLayout isistudyLayout = new javax.swing.GroupLayout(isistudy);
        isistudy.setLayout(isistudyLayout);
        isistudyLayout.setHorizontalGroup(
            isistudyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isistudyLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(isistudyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(guijava, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(javascript, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(isistudyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(script1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(python, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(java3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, isistudyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jjudul)
                .addGap(157, 157, 157))
        );
        isistudyLayout.setVerticalGroup(
            isistudyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(isistudyLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jjudul)
                .addGap(18, 18, 18)
                .addGroup(isistudyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desain)
                    .addComponent(script1))
                .addGap(45, 45, 45)
                .addGroup(isistudyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guijava)
                    .addComponent(python))
                .addGap(49, 49, 49)
                .addGroup(isistudyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(javascript)
                    .addComponent(java3))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        mainPanel.add(isistudy, "card6");

        javax.swing.GroupLayout bodypanelLayout = new javax.swing.GroupLayout(bodypanel);
        bodypanel.setLayout(bodypanelLayout);
        bodypanelLayout.setHorizontalGroup(
            bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodypanelLayout.createSequentialGroup()
                .addComponent(menupanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodypanelLayout.setVerticalGroup(
            bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menupanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labelconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelconfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelconfirmActionPerformed

    private void labelemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelemailActionPerformed

    private void facebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facebookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facebookActionPerformed

    private void tf_linkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_linkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_linkActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        //
        mainPanel.add(isiHome);
        mainPanel.repaint();
        mainPanel.revalidate();
       
    }//GEN-LAST:event_homeActionPerformed

    private void studyingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studyingActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        //
        mainPanel.add(isistudy);
        mainPanel.repaint();
        mainPanel.revalidate();
        
                
    }//GEN-LAST:event_studyingActionPerformed

    private void addfriendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addfriendActionPerformed
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        // 
        mainPanel.add(isiaddfriend);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_addfriendActionPerformed

    private void settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingActionPerformed
        about n = new about();
        n.setVisible(true);
        
    }//GEN-LAST:event_settingActionPerformed

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
        // TODO add your handling code here:
        String user = labelnama.getText();
        String mail = labelemail.getText();
        String pas = labelpass.getText();
        String pascon = labelconfirm.getText();
        JOptionPane.showMessageDialog(this, "selamat datang\n" + "username : " + user +"\n"+ "email : " + mail);  
        
    }//GEN-LAST:event_btnsignupActionPerformed

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
        // TODO add your handling code here:
      btn_logout.setBackground(new Color(999999));
      
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
        // TODO add your handling code here:
        btn_logout.setBackground(Color.WHITE);
    }//GEN-LAST:event_btn_logoutMouseExited

    private void btn_logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMousePressed
        // TODO add your handling code here:
        btn_logout.setBackground(new Color(808080));
    }//GEN-LAST:event_btn_logoutMousePressed

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // TODO add your handling code here:
        int keluar = JOptionPane.YES_NO_OPTION;
        int keluar2 = JOptionPane.showConfirmDialog(this,"apakah anda yakin mau keluar","PERINGATAN", keluar);
        if (keluar2 == 0) {
         // System.exit(0);
         dispose();
        }else{
            
        }
    }//GEN-LAST:event_btn_logoutMouseClicked

    /* @param args the command line arguments
    */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new mainview().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addfriend;
    private javax.swing.JPanel bodypanel;
    private javax.swing.JButton bt_link;
    private javax.swing.JPanel btn_logout;
    private javax.swing.JButton btnsigin;
    private javax.swing.JButton btnsignup;
    private javax.swing.JLabel confirm;
    private javax.swing.JLabel copyright;
    private javax.swing.JLabel created;
    private javax.swing.JButton desain;
    private javax.swing.JLabel email;
    private javax.swing.JButton facebook;
    private javax.swing.JButton guijava;
    private javax.swing.JButton home;
    private javax.swing.JPanel isiHome;
    private javax.swing.JPanel isiaddfriend;
    private javax.swing.JPanel isistudy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton java3;
    private javax.swing.JButton javascript;
    private javax.swing.JLabel jjudul;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel juduladd;
    private javax.swing.JTextField labelconfirm;
    private javax.swing.JTextField labelemail;
    private javax.swing.JTextField labelnama;
    private javax.swing.JPasswordField labelpass;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menupanel;
    private javax.swing.JLabel password;
    private javax.swing.JButton python;
    private javax.swing.JButton script1;
    private javax.swing.JButton setting;
    private javax.swing.JButton studying;
    private javax.swing.JTextField tf_link;
    private javax.swing.JLabel username;
    private javax.swing.JLabel welcome;
    private javax.swing.JButton whatsapp;
    private javax.swing.JLabel with;
    // End of variables declaration//GEN-END:variables

    private void setVisible(int MAXIMIZED_HORIZ) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
